services:

  telegram-bot:
    image: telegram-bot
    build:
      context: go-telegram/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: go-telegram/.env

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_DEBUG=true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  email-lambda:
    image: email-lambda
    build:
      context: email_lambda/
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
    entrypoint: ["/usr/local/bin/aws-lambda-rie"]
    command: ["./main"]


volumes:
  ollama:
    name: ollama