[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.29",
    "fastapi>=0.115.0",
    "llama-index-llms-ollama>=0.3.3",
    "llama-index>=0.11.14",
    "pydantic>=2.9.2",
]
